{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "acme-app.serviceAccountName" . }}
  labels:
    {{- include "acme-app.labels" . | nindent 4 }}
  {{- if or .Values.annotations .Values.serviceAccount.annotations }}
  annotations:
    {{- with .Values.annotations }}
    {{ toYaml . | indent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
